---
title: "BizKit 1.0"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
# NOTE: SET YOUR WORKING DIRECTORY HERE (LOCATION OF REPO)
# setwd()

if (!require(flexdashboard)) {
  install.packages("flexdashboard")
}
if (!require(shiny)) {
  install.packages("shiny")
}
if (!require(leaflet)) {
  install.packages("leaflet")
}
if (!require(highcharter)) {
  install.packages("highcharter")
}
if (!require("rgdal")) {
  install.packages("rgdal")
}
if (!require(sp)) {
  install.packages("sp")
}
if (!require(maps)) {
  install.packages("maps")
}
if (!require(ggmap)) {
  install.packages("ggmap")
}
if (!require(maptools)) {
  install.packages("maptools")
}

library(flexdashboard)
library(shiny)
library(leaflet)
library(highcharter)
library("rgdal")
library(sp)
library(maps)
library(ggmap)
library(maptools)

centroids <- read.csv(file="data/csv/suburb_centroids.csv", header=TRUE, sep=",")
```

Inputs {.sidebar}
-----------------------------------------------------------------------

Microarray data matrix for 80 experiments with Saccharomyces Cerevisiae
organism extracted from R's `biclust` package.

Sebastian Kaiser, Rodrigo Santamaria, Tatsiana Khamiakova, Martin Sill, Roberto
  Theron, Luis Quintales, Friedrich Leisch and Ewoud De Troyer. (2015). biclust:
  BiCluster Algorithms. R package version 1.2.0.
  http://CRAN.R-project.org/package=biclust
  
```{r}
latitude.max <- max(centroids$lat)
latitude.min <- min(centroids$lat)
longitude.max <- max(centroids$long)
latitude.min <- max(centroids$long)
# Rate at which to flag high download traffic
# Rate at which to flag high download traffic
selectInput("clusterNum", label = h3("Cluster number"), 
            choices = list("1" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5), 
            selected = 1)

```

Row
-----------------------------------------------------------------------

```{r}
## Read suburbs data
url <- "data/geoJSON/Suburbs.geojson"
res <- readOGR(url, layer="OGRGeoJSON" ,verbose = FALSE)

## Subset data for Adelaide area only
url <- "data/csv/Adelaide_Zips.csv"
adelaide.zips <- read.csv(url)
unique.zips <- unique(adelaide.zips$Post.Code)

match.indices <- which(res$POSTCODE %in% unique.zips)
subset.data <- res[na.omit(match.indices),]

## Read bike lane data
tkml <- readOGR("data/KMZ/bike_routes.kml", "templayer0", verbose=FALSE)

## Major and minor roads
major.roads <- readOGR("data/KMZ/major_roads.kml", "MajorRoads_Layer", verbose=FALSE)
minor.roads <- readOGR("data/KMZ/minor_roads.kml", "MinorRoads_Layer", verbose=FALSE)


## Initialize color bins for legend
testvector <- c(1:length(subset.data))
bins <- c(0, 100, 200, 300, 400, 500, 600, Inf)
pal <- colorBin("YlOrRd", domain = testvector, bins = bins)

output$map <- renderLeaflet({

  x <- leaflet() %>%
    addTiles() %>%
    addMarkers(data = centroids, 
               lng = centroids$long, 
               lat = centroids$lat, 
               layerId = ~centroids$id, 
               popup = ~centroids$suburb, 
               clusterOptions = markerClusterOptions()) %>%
    addPolygons(data = subset.data) %>%
    addPolygons(
      data = subset.data,
      fillColor = ~pal(testvector),
      weight = 2,
      opacity = 1,
      color = "white",
      dashArray = "3",
      fillOpacity = 0.7) %>%
    addPolylines(data = major.roads, color="red") %>%
    addPolylines(data = minor.roads, color="salmon") %>%
    addPolylines(data = tkml, color="green")
  
})

leafletOutput('map')  

```

Row
-----------------------------------------------------------------------

```{r}
click_marker <- eventReactive(input$map_marker_click, {

  x <- input$map_marker_click

  return(x$id)

})

data_for_chart <- reactive({

  return(centroids[centroids$id == click_marker(), ])

})

output$chart <- renderHighchart({

  highchart() %>%
    hc_chart(type = 'column') %>%
    hc_add_series(data = c(data_for_chart()$lat, 
                           data_for_chart()$long))

})

highchartOutput('chart')

```